name: Auto-Signed Commits

on:
  push:  
    branches:
      - '**'  # Runs on all branches

jobs:
  sign-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Get Current Branch
        id: get_branch
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Set up Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.VERIFIED_COMMIT_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.VERIFIED_COMMIT_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git commit --allow-empty -m "Automated Signed Commit"
          git push https://x-access-token:${{ secrets.VERIFIED_COMMIT_TOKEN }}@github.com/otaku0304/PDF_Password_Remover_Angular.git HEAD:$BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.VERIFIED_COMMIT_TOKEN }}
